// apps/angular-recipes/src/app/recipes/services/recipe-service.ts
import { inject, Injectable } from '@angular/core'
import type { Observable } from 'rxjs'

import type { RecipeDefinition } from '@shared/types'

import type { RecipeContentProvider } from '../providers/recipe-content-provider'
import { RECIPE_CONTENT_PROVIDER } from '../providers/recipe-content-provider.token'
import { demoRegistry } from '../registry/demo-registry'

/**
 * UI-facing façade that keeps pages focused on routing and presentation while
 * provider selection stays in the composition root.
 */
@Injectable({ providedIn: 'root' })
export class RecipeService {
  private readonly recipeContentProvider: RecipeContentProvider = inject(
    RECIPE_CONTENT_PROVIDER
  )

  public getRecipes(): Observable<RecipeDefinition[]> {
    return this.recipeContentProvider.getRecipes()
  }

  public getRecipeBySlug(slug: string): Observable<RecipeDefinition | null> {
    return this.recipeContentProvider.getRecipeBySlug(slug)
  }

  public getDemoMessage(recipe: RecipeDefinition | null): string {
    if (!recipe) {
      return 'Demo coming soon.'
    }

    return demoRegistry[recipe.demoKey]
  }
}

// apps/react-recipes/src/recipes/services/RecipeService.ts
import type { RecipeDefinition } from '@shared/types'
import type { ComponentType } from 'react'

import { recipeContentProvider } from '@/recipes/providers'
import { demoRegistry } from '@/recipes/registry/demoRegistry'

/**
 * Small façade that keeps React pages aligned with the Angular page → service →
 * provider flow.
 */
export class RecipeService {
  public async getRecipes(): Promise<RecipeDefinition[]> {
    return recipeContentProvider.getRecipes()
  }

  public async getRecipeBySlug(slug: string): Promise<RecipeDefinition | null> {
    return recipeContentProvider.getRecipeBySlug(slug)
  }

  public getDemoComponent(recipe: RecipeDefinition): ComponentType {
    return demoRegistry[recipe.demoKey]
  }
}
