// apps/react-recipes/src/app/layout/MainLayout.tsx
import { Outlet } from 'react-router-dom'

/**
 * Top-level layout shared by all React routes.
 */
export default function MainLayout() {
  return (
    <div className="app">
      <main className="content">
        <Outlet />
      </main>

      <footer className="footer">
        <small>Frontend Recipes – React / TypeScript patterns</small>
      </footer>
    </div>
  )
}

// apps/angular-recipes/src/app/layout/main-layout.ts
import { Component } from '@angular/core'

/**
 * Top-level layout shared by all Angular routes.
 */
@Component({
  standalone: true,
  selector: 'app-main-layout',
  template: `
    <div class="app">
      <main class="content">
        <ng-content />
      </main>

      <footer class="footer">
        <small>Frontend Recipes – Angular / TypeScript patterns</small>
      </footer>
    </div>
  `,
})
export class MainLayoutComponent {}
