// apps/angular-recipes/src/app/components/recipe-page-layout.ts
import { Component, input } from '@angular/core'
import { RouterLink } from '@angular/router'

/**
 * Shared page shell for recipe details.
 */
@Component({
  standalone: true,
  selector: 'app-recipe-page-layout',
  imports: [RouterLink],
  template: `
    <section class="recipe-page">
      <div class="recipe-page__container">
        <a class="recipe-page__back" routerLink="/">← Back to recipes</a>

        <header class="recipe-page__header">
          <h2>{{ title() }}</h2>
          @if (description()) {
            <p>{{ description() }}</p>
          }
        </header>

        <div class="recipe-page__content">
          <ng-content />
        </div>
      </div>
    </section>
  `,
})
export class RecipePageLayoutComponent {
  public readonly title = input.required<string>()
  public readonly description = input<string>()
}

// apps/react-recipes/src/components/RecipePageLayout.tsx
import type { ReactNode } from 'react'
import { Link } from 'react-router-dom'

type RecipePageLayoutProps = {
  title: string
  description?: string
  children?: ReactNode
}

/**
 * Shared page shell for recipe details.
 */
export default function RecipePageLayout({
  title,
  description,
  children,
}: RecipePageLayoutProps) {
  return (
    <section className="recipe-page">
      <div className="recipe-page__container">
        <Link className="recipe-page__back" to="/">
          ← Back to recipes
        </Link>

        <header className="recipe-page__header">
          <h2>{title}</h2>
          {description ? <p>{description}</p> : null}
        </header>

        <div className="recipe-page__content">{children}</div>
      </div>
    </section>
  )
}
