// apps/angular-recipes/src/app/components/recipe-section.ts
import { Component, input } from '@angular/core'

import type { RecipeSectionDefinition } from '@shared/types'

import { MarkdownContentComponent } from './markdown-content'

/**
 * Renders a single recipe section and optionally hosts a demo component.
 */
@Component({
  standalone: true,
  selector: 'app-recipe-section',
  imports: [MarkdownContentComponent],
  template: `
    <section class="recipe-section">
      <h2 class="recipe-section__title">{{ section().title }}</h2>
      <div class="recipe-section__content">
        <app-markdown-content [content]="section().content" />
      </div>
      <ng-content />
    </section>
  `,
})
export class RecipeSectionComponent {
  public readonly section = input.required<RecipeSectionDefinition>()
}

// apps/react-recipes/src/components/RecipeSection.tsx
import type { RecipeSectionDefinition } from '@shared/types'
import type { ReactNode } from 'react'

import MarkdownContent from '@/components/MarkdownContent'

type RecipeSectionProps = {
  section: RecipeSectionDefinition
  children?: ReactNode
}

/**
 * Renders a single recipe section and optionally hosts a demo component.
 */
export default function RecipeSection({
  section,
  children,
}: RecipeSectionProps) {
  return (
    <section className="recipe-section">
      <h2 className="recipe-section__title">{section.title}</h2>
      <div className="recipe-section__content">
        <MarkdownContent content={section.content} />
      </div>
      {children}
    </section>
  )
}
